// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwVvSW5zMd-bJAGyI3rk7BCz3BJeTN1Q',
    appId: '1:626625303464:web:061e7863bcebe1d01bc39d',
    messagingSenderId: '626625303464',
    projectId: 'fridge-manager-cf89d',
    authDomain: 'fridge-manager-cf89d.firebaseapp.com',
    storageBucket: 'fridge-manager-cf89d.firebasestorage.app',
    measurementId: 'G-SFD31WST1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqNyKpa7pND3OHMsoj2uf_IepVH1p1pis',
    appId: '1:626625303464:android:271328bca6e7e10e1bc39d',
    messagingSenderId: '626625303464',
    projectId: 'fridge-manager-cf89d',
    storageBucket: 'fridge-manager-cf89d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8sh48C_EH8kiVdahqgyc9SNcM28HQpc',
    appId: '1:626625303464:ios:24a233289e0a26d91bc39d',
    messagingSenderId: '626625303464',
    projectId: 'fridge-manager-cf89d',
    storageBucket: 'fridge-manager-cf89d.firebasestorage.app',
    iosBundleId: 'com.example.fridgeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8sh48C_EH8kiVdahqgyc9SNcM28HQpc',
    appId: '1:626625303464:ios:24a233289e0a26d91bc39d',
    messagingSenderId: '626625303464',
    projectId: 'fridge-manager-cf89d',
    storageBucket: 'fridge-manager-cf89d.firebasestorage.app',
    iosBundleId: 'com.example.fridgeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWwVvSW5zMd-bJAGyI3rk7BCz3BJeTN1Q',
    appId: '1:626625303464:web:d28d7eab72b7fe201bc39d',
    messagingSenderId: '626625303464',
    projectId: 'fridge-manager-cf89d',
    authDomain: 'fridge-manager-cf89d.firebaseapp.com',
    storageBucket: 'fridge-manager-cf89d.firebasestorage.app',
    measurementId: 'G-RYE6CTY6N7',
  );
}
